function [classNumber] = MAP_class3(dataPoint, ...
								meanA,covarA,n_A, ...
								meanB,covarB,n_B, ...
								meanC,covarC,n_C)

	function dist = getDist(dataPoint_t, mean_x,covar_x)
		dist= transpose(dataPoint_t'-mean_x')*inv(covar_x)*(dataPoint_t'-mean_x');
	end
	
	decisionAB=getDist(dataPoint, meanB,covarB) ...
		-getDist(dataPoint, meanA,covarA) ...
		-2*log(n_B/n_A) ...
		-log(det(covarA)/det(covarB));
	decisionBC=getDist(dataPoint, meanC,covarC) ...
		-getDist(dataPoint, meanB,covarB) ...
		-2*log(n_C/n_B) ...
		-log(det(covarB)/det(covarC));
	
	decisionCA=getDist(dataPoint, meanA,covarA) ...
		-getDist(dataPoint, meanC,covarC) ...
		-2*log(n_A/n_C) ...
		-log(det(covarC)/det(covarA));
	
	if (decisionAB > 0) && (decisionCA < 0)
		classNumber=1;
	elseif (decisionBC > 0) && (decisionAB < 0)
		classNumber=2;
	elseif (decisionCA > 0) && (decisionBC < 0)
		classNumber=3;
	else
		classNumber=-1; % WTF?
	end


end